### ISSUE TITLE
possible incompatibility with latest vrchat supported unity version/ vrchat creator companion

### ISSUE THREAD

**Issue by Joeockcicicicifi** [SuperFlue/VRC-Auto-Toggle-Creator#4]
i am having a possible compatibility issue with the latest version of unity supported by vrchat where o cannot add game objects into the game object field of the animator please let me know if or when this is fixed or if more detail is needed thx

**Comment by Wizuky** [comment]
Experiencing the same issue here.

**Comment by SuperFlue** [comment]
Apparently I had forgotten to enable notifications here. This issue has been fixed with the latest release.
This also includes migration to use the Creator Companion repository format.
